### ISSUE TITLE
Update guidelines for footnote placement in parent sections

### ISSUE THREAD

**Issue by AndersEkl** [nlbdev/nordic-accessible-epub-guidelines#10]
Originally posted by @martinpub.

Current guidelines [say](https://format.mtm.se/nordic_epub/2020-1#notes-and-note-references) "Footnotes are to be placed in an `<aside>` at the end of the relevant `<section>`".

However, in the following example, we have top section content with noterefs, but the notes will be placed at the very end, after any subsections which may also include notes.

```xml
<section aria-labelledby="d5e14309" epub:type="bodymatter chapter" id="d5e14302" role="doc-chapter">
	<h2 id="d5e14309">[Chapter heading]</h2>
	<blockquote>
		<p>[quote text].<a class="noteref" epub:type="noteref" href="V005138-013-chapter.xhtml#d5e15941" id="d5e14326" role="doc-noteref">1</a></p>
	</blockquote>
	<section>
		<h3>[subsection heading]</h3>
		[subsection contents]
	</section>
	[possibly other subsections]
	
    <aside epub:type="footnote" id="d5e15941" role="doc-footnote">
	<p id="d5e15943">[footnote text]</p><p><a href="V005138-013-chapter.xhtml#d5e14326" role="doc-backlink">Gå tillbaka till notreferensen.</a></p>
    </aside>
</section>
```

Wouldn't the placement of the note text in these cases be just before the opening of a following subsection? In this way the notes will also be placed according to the noteref order, which seems logical.

I know reading systems might present the note texts interactively in some way (e.g. Thorium), so it might not be a big deal, but perhaps this is still an improvement. The suggestion is to consider this example and change/clarify note placement in a future update to the guidelines.

**Comment by oscarlcarlsson** [comment]
I think that this is a given solution. Having the footnotes at the end of each section instead of before the next sub-section is confusing to me even when i know why we do it this way. It a title uses symbols or numbered footnotes starting from 1 on each page, the notes would not follow in a logical order for the reader.

**Comment by AndersEkl** [comment]
This was handled in revising the whole note section.
