### ISSUE TITLE
Consider specifying how to handle/preserve links in source files

### ISSUE THREAD

**Issue by AndersEkl** [nlbdev/nordic-accessible-epub-guidelines#11]
Originally written by @martinpub 

Links in source files are currently not mentioned, perhaps they should.

Not sure preservation is desirable/doable in all cases but source files can include links of different types, e.g.:

- URLs, very common in footnotes/references. Not necessarily links, occur also in text-only form in PDFs.
- External links that are real links (in EPUB source files, but could potentially also be included in open PDFs)
- Internal links that are real links (in EPUB source files)

It would be good if the guidelines specified the handling of these different kinds of links.

Comment by @josteinaj 

Also worth noting is that epubcheck is validating the syntax of links, and some times the links in the original, even when the OCR is correct, is not valid according to epubcheck. Manually fixing the link vs preserving the original text?

Comment by @martinpub 

Great addition @josteinaj. I would say if we were to fix these links we would be busy, even though it will increase accessibility.
Note: this consideration should include mailto links for email addresses, whose treatment should also be clarified.

**Comment by AndersEkl** [comment]
If we decide to not mark up links as hyperlinks, we should mention it as a deviation from WCAG.

**Comment by TorilBWM** [comment]
Preserve all links in the source material seems to us the most desirable solution.

**Comment by AndersEkl** [comment]
We had a discussion about this when we went through the issues and prioritised them, and we discussed the issues of taking responsibility for the validity of links, making sure they don't point to any dubious or malicious content etc.

**Comment by TorilBWM** [comment]
We had not considered this potential problem. But I have to admit that "we should mention it as a deviation from WCAG" does not sit easily with me.

**Comment by AndersEkl** [comment]
Perhaps preserving already active links in for instance EPUB source files, but not making active links out of URLs in printed source materials?

**Comment by oscarlcarlsson** [comment]
Preserving active links sounds like a good middle ground here.
