### ISSUE TITLE
Consider adding guidance for source books with text boxes containing other text boxes

### ISSUE THREAD

**Issue by AndersEkl** [nlbdev/nordic-accessible-epub-guidelines#12]
Originally written by @martinpub

We have seen a couple of productions lately with nested `<aside class="text-box">`s. I think it's technically valid HTML5, but unsure about accessibility (asides are landmark elements).

Anyway, it might be a good idea to at least mention nested text-boxes in source material, along with markup guidance.

**Comment by AndersEkl** [comment]
The `<aside>` element should be used when the content is secondary, otherwise `<div>` should be used. If you nest two `<aside>` elements, that would suggest that the nested `<aside>` is secondary in the context of the first `<aside>`. I would suggest to never nest `<aside>` elements and, if a text box occurs within secondary content, to use `<div>` for any such content.

**Comment by TorilBWM** [comment]
We would like to retain the option for nested `<aside>` elements. One example is a glossary inside a text box.

**Comment by AndersEkl** [comment]
@TorilBWM how would that make sense semantically? Secondary content in content that is already secondary. And wouldn't a glossary simply be a `<dl>` element? And you also need to consider the fact that `<aside>` elements are automatically landmarks. That means we shouldn't use `<aside>` more than absolutely necessary.

**Comment by martinpub** [comment]
TODO after editors' meeting: Write note about nested boxes. Suggest `<div class="text-box">` for aside children.
