### ISSUE TITLE
Text extraction/descriptions for inline images

### ISSUE THREAD

**Issue by AndersEkl** [nlbdev/nordic-accessible-epub-guidelines#17]
Originally written by @martinpub

It is not very common, but text extraction/image description needs might occur for inline images. Perhaps this should be handled in the guidelines?

See also #16

**Comment by oscarlcarlsson** [comment]
How should this be inserted to not distrupt the flow of the text? Should the text for the image description be added at the end of the paragraph if a more exstensive image description was needed? 
Could alt-text be sufficient in most of these cases?

**Comment by martinpub** [comment]
I lean towards your second suggestion @oscarlcarlsson, alt-text will probably be sufficient. And other structures might be cumbersome to formulate some general rule for. I don't have any examples right here, but for complex images presented inline somehow, there is also the solution to "blockify" them in markup.

**Comment by AndersEkl** [comment]
Yes, I agree. In general, alt-text should be sufficient and is what I think the guidelines should require. If an inline image does need a more elaborate description it would have to be made into a regular block image.
