### ISSUE TITLE
Consider DPUB WAI-ARIA in future work on the guidelines

### ISSUE THREAD

**Issue by AndersEkl** [nlbdev/nordic-accessible-epub-guidelines#20]
Originally written by @GauteR 

A few months ago, the first public working draft of the DPUB WAI-ARIA Module 1.1 was published on W3C (although it's not a recommendation yet).

Maybe this should be considered in future work for the Nordic guidelines?

[Digital Publishing WAI-ARIA Module 1.1](https://www.w3.org/TR/dpub-aria-1.1/)

Comment by @martinpub 

Yes, I agree. Future updates will need to consider this, and updates to other related specs, such as EPUB 3.x, etc.

**Comment by AndersEkl** [comment]
We will go through the list of roles and see if there are any that should be specifically mentioned in the guidelines.

**Comment by oscarlcarlsson** [comment]
Do we want the roles be added to each section where we want the producers to add them or do we want a general section of the guidelines where we bring it up?

**Comment by oscarlcarlsson** [comment]
Looking at the list, there are a few that i assume that we never use, at least not at MTM (e.g. doc-glossref, doc-pagefooter/-pageheader, doc-pullquote). Are there any roles that we never want the producers to use?
