### ISSUE TITLE
Figures and tables should have IDs

### ISSUE THREAD

**Issue by AndersEkl** [nlbdev/nordic-accessible-epub-guidelines#21]
Originally written by @samimaattaCelia

We should clarify in the guidelines that figures/images and tables need IDs, so they can be referenced in the navigation document.

For figures it could be `id="fig1"` etc.
For tables it could be `id="tab1"` etc.

Although I don't have any information on how the reading apps support the use of the navigation document, I would imagine it's useful in the future to mention this in the guidelines - or at least demonstrate the use in the existing examples of figure markup.

Comment by @josteinaj 

Does this only apply to tables or figures that should be referenced from the navigation document? Do you have any examples of cases where figures or tables are referenced from the navigation document? Would it be an alternative to wrap the tables and figures in a section element, so that they become part of the outline of the book?

Comment by @samimaattaCelia

> Does this only apply to tables or figures that should be referenced from the navigation document?

At first I assumed that guidelines actually would require the list of images in the navigation document, but now I see that the section **2.6.1.3 Landmarks** was referencing only hyperlinking the list of images/tables in the book content and not in the navigation document itself. Now it makes sense to me that IDing figures and tables wasn't a thing in the guidelines.

Here is a code snippet of how it could be done in the navigation document (Benetech's suggestion):
```
<nav epub:type="loi" aria-labelledby="list_figure">
<h1 id="list_figure">List of figures</h1>
<ol>
<li><a href="374489_2-007-chapter.xhtml#fig1">[figcaption of the first figure]</a></li>
<li><a href="374489_2-007-chapter.xhtml#fig2">[figcaption of the second figure]</a></li>
…
</ol>
</nav>
```

> Would it be an alternative to wrap the tables and figures in a section element, so that they become part of the outline of the book?

I don't think this would be effectively a better of way letting the user cycle through or find the images in the book (which I think the navigation document is fundamentally trying to achieve - any other interpretations?), so I would say no to this solution.

I also don't have experience on how reading apps actually handle images, as in is it possible to cycle through them as a screen reader would cycle through links on a webiste?

Do you see this as a valuable thing for the guidelines?

Comment by @josteinaj 

Ok, I see now.

If a list of illustrations or tables are included, then IDs are implicitly required I guess? We could require IDs, but I think in most cases they would not be used?

Comment by @samimaattaCelia

That's my understanding as well that the IDs would only be used for navigation and their added value is questionable.

Even so I would leave this issue open for future guideline discussions as I think we have now demonstrated how it could be done and what the motivation to do so would be.

**Comment by oscarlcarlsson** [comment]
i see no issue with including id:s for figures and tables. if nothing else, it could be a good safeguard for future updates where it could be needed.

**Comment by oscarlcarlsson** [comment]
Do we want these to be something specific or could they be any ID?

**Comment by samimaattaCelia** [comment]
Jumping into answer. I think they should be of form "figure-1", "figure-2" and so on for easy regexing (if needed). Same for tables.

**Comment by oscarlcarlsson** [comment]
@samimaattaCelia i guess any sequential order work here? at the moment one of our producers is using img-001 etc. for image id:s.

**Comment by oscarlcarlsson** [comment]
Do we want another id for the cover? Cover images are already excluded from the rest of the naming structure.

**Comment by jonaslil** [comment]
I can't see any use for an id for the cover.

I'm not quite sure about this in general. I think there is a virtue in keeping markup as simple as possible. If the id:s will not be used in most cases, wouldn't it be better to add them only when they are needed?

**Comment by oscarlcarlsson** [comment]
I agree. lets leave the cover out of it.

I think that if we implement this, we might as well use it for all of our produced titles since it's hard to predict when we might need to use the id's for regex-fuctions etc.

Since one of our producers is already using this and that none of us have reacted to it, i don't think it makes the markup that much more complex.

**Comment by martinpub** [comment]
I agree with @jonaslil, use when needed. But it should def. be allowed. For various scripting purposes, identification could use XPath etc., in absence of ID attributes. Or use some XML-based way of assigning IDs (e.g. XQuery).

**Comment by jonaslil** [comment]
It definitely does not hurt to have the id:s. I was mostly a bit hesitant about adding new requirements that may be easy to meet for some producers but not for all, and that can give rise to irrelevant validation errors. Maybe requiring id:s should be up to the ordering agency - but adding them should always be allowed.

**Comment by oscarlcarlsson** [comment]
agree that it shouldn't fail validations if id:s are included.

we already allow it in the validator. so, just adding a comment that id:s might be asked for in either editing instructions or by specific agencies, then?

**Comment by martinpub** [comment]
Yes, it's fine.
