### ISSUE TITLE
Clarify initial letter case of alt text values

### ISSUE THREAD

**Issue by AndersEkl** [nlbdev/nordic-accessible-epub-guidelines#24]
Originally written by @martinpub 

Table in "5.2.3 Image Alternative Text Values" has initial capital letters, but the list of English values in "3.4.3.2 Alt-texts" has initial lowercase letters for the values. This should be aligned.

We used to have e.g. "image", so I guess we should stick to lowercase here? Ping @AndersEkl

**Comment by jonaslil** [comment]
If these alt texts are sometimes left in the final book, and are not just placeholders, they should end with a full stop to ensure that screenreaders pause after the alt text. For me, this speaks for having initial capital letters.

**Comment by AndersEkl** [comment]
Good point. The idea is that these alt texts should NOT be in the final book, but it seems like a good idea to ensure the best possible handling of them if they should end up there anyway.

**Comment by oscarlcarlsson** [comment]
We still use the generic alt-texts in our productions at the moment. So, fine tuning them with punctuation and capital letters sounds like a good approach.
