### ISSUE TITLE
Add non-verse div class to allow the use of line/linenum-formatted content

### ISSUE THREAD

**Issue by AndersEkl** [nlbdev/nordic-accessible-epub-guidelines#28]
Originally written by @martinpub 

Currently, the validation rules only allow `<span class="line">`  etc. in a `<div class="verse">` parent element.

There is non-verse content where a line by line and line numbering markup would be well suited, e.g. reproduced manuscripts, drafts, original latin texts, or content for text analysis in HE methodology books.

Perhaps the guidelines could be updated to allow non-verse applications of line by line and line numbering markup? Probably, this would require introducing a new class for a non-verse `<div>` wrapper. Not sure about the proper naming of such a class, though, maybe "verbatim"?

Ping @AndersEkl 

Comment by @AndersEkl 

I see no problem with extending the use of line/linenum. Is this something that needs to be addressed immediately in the guidelines, or can it wait until the next revision? We could still have the validator allowing it outside of verse.

Comment by @martinpub 

No, this could actually wait. However there were some issues according to the validator devs with allowing them globally (outside poem wrapper div) in RelaxNG. I guess we should move this to guidelines 2021-1 and still see if the validator rules could be loosened up a little to allow them in the meantime.

Just wanted to add another (important) content use case: books with easy-to-read text typeset with what in Swedish is referred to as ["frasanpassat radfall"](https://www.mtm.se/var-verksamhet/lattlast/att-skriva-lattlast/).

**Comment by martinpub** [comment]
See also #50

**Comment by oscarlcarlsson** [comment]
we should probably add a separate css-rule for non-verse linenum/line-content.
we could have a look at the titles that we are producing with "frasanpassat radfall" for inspiration
