### ISSUE TITLE
Fixing the notes section

### ISSUE THREAD

**Issue by AndersEkl** [nlbdev/nordic-accessible-epub-guidelines#3]
Remove the usage of doc-endnote and see if there are any further changes or clarifications that are needed.

**Comment by AndersEkl** [comment]
We need to check the notes section in the Digital Publishing Knowledge Base to see if there are other things besides the deprecated doc-endnote role that needs fixing.

**Comment by oscarlcarlsson** [comment]
Notes in tables from the Daisy KB could be worth looking into here.

**Comment by AndersEkl** [comment]
In the current version of the guidelines we say that note references must **not** be marked up with `<sup>` and that CSS styling will be used to display the note references correctly. The KB says something similar but points out that until the `doc-footnote` role has better support (I guess they mean in assistive technology), using `<sup>` may serve a purpose, although slightly verbose. What do we think about this? Should we keep the rule about not using `<sup>`? @martinpub @jonaslil @oscarlcarlsson

**Comment by oscarlcarlsson** [comment]
does <sup> on footnotes help with anything for screen readers? if not, i don't think we should add it.

**Comment by AndersEkl** [comment]
It signals that something is up. It doesn't provide proper semantic information. But I think we should keep the rule as it is, i e no `<sup>`.

**Comment by oscarlcarlsson** [comment]
agree!

**Comment by AndersEkl** [comment]
Or is it? I am a bit confused by example 5...

**Comment by AndersEkl** [comment]
I must say I am a bit confused about the whole page about notes. First it says that footnotes should be placed in `<aside>` and endnotes in `<ol>`. Then comes the examples 4 and 5 describing back links and in both cases `<div>` is used instead of (?) the previously suggested markup. I don't get that.

**Comment by jonaslil** [comment]
I agree that the examples are confusing. I actually took this up recently in the Better epub from Indesign working group. The others suggested that I should reach out directly to Matt G. for clarification of the Daisy KB page on notes. I could do that.

**Comment by AndersEkl** [comment]
> I agree that the examples are confusing. I actually took this up recently in the Better epub from Indesign working group. The others suggested that I should reach out directly to Matt G. for clarification of the Daisy KB page on notes. I could do that.

Yes, please do! I have written a new section on notes in the guidelines document. Will commit it in a second. You can look at that, maybe show it to Matt and then get back to me about it, if anything needs changing.

**Comment by martinpub** [comment]
Great! I agree that `<sup>` should not be used.

**Comment by AndersEkl** [comment]
Reminder for myself: Add sub-headings for footnotes and endnotes (all numbered notes).
