### ISSUE TITLE
Consistently use "rearcover" for rearcover class

### ISSUE THREAD

**Issue by AndersEkl** [nlbdev/nordic-accessible-epub-guidelines#30]
Originally written by @martinpub 

Correct 3.1.

**Comment by martinpub** [comment]
Hi @AndersEkl, @jonaslil and @oscarlcarlsson,

Was going to fix this but I just thought, should we rather use "back cover" consistently? Isn't "back cover" the more frequently used term? We also use "back matter", so this would be in line with that.

However, it involves changing the class name as well, which may not be ideal. What do you think?

**Comment by martinpub** [comment]
Note, the controlled term to use in English for `@aria-label` is currently defined as "Back cover", wasn't sure if the original thought was to preserve that and only correct the reference in the table so that it aligns with rearcover.

**Comment by martinpub** [comment]
I think I still need feedback from you guys, how important is keeping the class name?

**Comment by AndersEkl** [comment]
I don't have any strong opinions in this matter. I think the rear/back cover is more important for the type of books the libraries produce.

**Comment by jonaslil** [comment]
I prefer back cover as a term, I think it is more widely used. Googling confirms this. 

I would be in favour of changing the classname to "backcover" in 3.3.1.

**Comment by oscarlcarlsson** [comment]
Me too.
