### ISSUE TITLE
Pagebreak positioning in lists and tables

### ISSUE THREAD

**Issue by AndersEkl** [nlbdev/nordic-accessible-epub-guidelines#33]
Originally written by @josteinaj 

Should there be something in the guidelines about positioning of pagebreaks when they occur inside lists and tables?

- do we allow pagebreaks in the middle of a list item?
- if the pagebreak is between to list items, should it be placed at the end of the preceding or the beginning of the following list item?
- do we allow pagebreaks in the middle of a table cell?
- do we allow pagebreaks in the middle of a table row?
- if the pagebreak is between to table cells, should it be placed at the end of the preceding or the beginning of the following table cell?
- if the pagebreak is between to table rows, should it be placed at the end of the preceding or the beginning of the following table row?

Comment by @AndersEkl 

> 
> 
> Should there be something in the guidelines about positioning of pagebreaks when they occur inside lists and tables?
> 
>     * do we allow pagebreaks in the middle of a list item?
Yes, we should allow that. It is not uncommon to have pagebreaks in the middle of a list item.
> 
>     * if the pagebreak is between to list items, should it be placed at the end of the preceding or the beginning of the following list item?
Probably at the end of the preceeding.
> 
>     * do we allow pagebreaks in the middle of a table cell?
Can't think of any case where that would occur. So, probably no!
> 
>     * do we allow pagebreaks in the middle of a table row?
Same thing here, can't really think of any such case.
> 
>     * if the pagebreak is between to table cells, should it be placed at the end of the preceding or the beginning of the following table cell?
I don't think it should ever be between two table cells on the same row.
> 
>     * if the pagebreak is between to table rows, should it be placed at the end of the preceding or the beginning of the following table row?
At the end of the preceeding, I would say.

Maybe this needs to be included in the guidelines.

**Comment by TorilBWM** [comment]
We agree that the pagebreak should be placed at the end of the preceeding list item / table row. We include this in our instructions.
