### ISSUE TITLE
Annotations

### ISSUE THREAD

**Issue by AndersEkl** [nlbdev/nordic-accessible-epub-guidelines#36]
Originally written by @AndersEkl 

We have not mentioned annotations in v. 1.0.

**Comment by martinpub** [comment]
How is annotations defined in this context?

**Comment by AndersEkl** [comment]
I don't remember, quite frankly. I just transferred the issue from the old repo.

**Comment by martinpub** [comment]
In 2015-1, "annotations" are defined as "Shorter marginalia". So I think it is similar to `<aside class="text-box">`. We could clarify the scope of asides/text-boxes/"annotations" in the update.

**Comment by AndersEkl** [comment]
I was originally thinking of specific markup for annotations, which is now deprecated.

**Comment by martinpub** [comment]
In [Schema.org Accessibility Properties for Discoverability Vocabulary](https://www.w3.org/community/reports/a11y-discov-vocab/CG-FINAL-vocabulary-20230718/#annotations), "annotations" as an accessibility feature is defined as "The resource includes annotations from the author, instructor and/or others."
