### ISSUE TITLE
Epigraphs

### ISSUE THREAD

**Issue by AndersEkl** [nlbdev/nordic-accessible-epub-guidelines#38]
Originally written by @josteinaj

Should epigraph markup be described?

We previously used:

- `<aside class="epigraph" epub:type="epigraph">…</aside>` when the epigraph had a headline
- `<p class="epigraph" epub:type="epigraph">…</p>` when the epigraph was inside another epigraph
- `<blockquote class="epigraph" epub:type="epigraph">…</blockquote>` otherwise

See:
- https://github.com/nlbdev/nlbpub/issues/24
- https://www.w3.org/TR/dpub-aria-1.0/#doc-epigraph

**Comment by AndersEkl** [comment]
There is a role for epigraphs in the DPUB WAI-ARIA spec. This is what we should be using, I think.

**Comment by martinpub** [comment]
Covered by #20.

**Comment by AndersEkl** [comment]
Covered by #20
