### ISSUE TITLE
Discuss figure description markup

### ISSUE THREAD

**Issue by AndersEkl** [nlbdev/nordic-accessible-epub-guidelines#4]
The suggested markup for figure descriptions on KB differs from ours. We did some testing of the markup back when we started on the 2020-1 guidelines, and decided on what we wrote there, but maybe we should look into this again now? Reading systems have changed since then.

**Comment by AndersEkl** [comment]
See for instance: https://daisy.github.io/transitiontoepub/best-practices/extended-desc/ExtendedDescriptionsBestPractices.html

**Comment by AndersEkl** [comment]
See also #22

**Comment by jonaslil** [comment]
I think this one is important and would be worthy of Prio 1.

We at Celia have been considering `<details>`. But will it create problems with synced audio?

**Comment by martinpub** [comment]
Yes, perhaps this could be considered Prio 1. It might be problematic in talking books, depending on how the RS implements this. But generally, I think details will need user input to expand the contents.

**Comment by oscarlcarlsson** [comment]
i'll add a details tag in our next batch of sample files that we send to our talking book producers to see how it works with synced audio.

**Comment by martinpub** [comment]
Any progress @oscarlcarlsson? If the MO playback in the RS would "open" the details element, this could be a nice fit.

**Comment by oscarlcarlsson** [comment]
We still have some isuses with our latest batch of sample files, so this has not been tested yet.

**Comment by AndersEkl** [comment]
Any news on testing, @oscarlcarlsson ?

**Comment by AndersEkl** [comment]
If `<details>` doesn't work properly with all AT then maybe we shouldn't use it now? The other examples given at KB doesn't seem functional to me. Maybe we should keep this as it is? @martinpub @jonaslil @oscarlcarlsson @lindheli

**Comment by jonaslil** [comment]
Noting this observation about `details` in Daisy KB, [Image Descriptions](http://kb.daisy.org/publishing/docs/html/images-desc.html):

> To use the element in EPUB publications, it is also recommended to put the element immediately after a closing figure tag when the description is for a figure. The element often does not work when included inside a figure.

I would still be interested to hear if `details` works with MO.

Some test reports with reading system + screenreader combinations can be found here: https://epubtest.org/results/topic/extended-descriptions/extdescription-010

**Comment by martinpub** [comment]
I believe the details method (yes, with details outside the figure element) should work well with screen readers, the issue is more with MO. I think @oscarlcarlsson has some results from the testing.

**Comment by jonaslil** [comment]
Been testing `details` a bit with NVDA and Thorium's read aloud. With NVDA, it works fine, unless you access the description using NVDA + D at the image that has the `aria-details` attribute, in which case the screenreader only reads the summary.

But the read aloud behaviour is disappointing. The only way to make it read even the summary is to open the element before you start using read aloud. (You can set it to open by default with the `open="open"`.) If you try to open the element while using read aloud Thorium throws you to the beginning of the file. Pausing or stopping read aloud before opening the element does not help. This almost seems like a bug they should fix.

**Comment by martinpub** [comment]
Thanks for the tests @jonaslil! My colleague confirmed good results with JAWS and Thorium on Windows.

Yes, I noted the Thorium read aloud results, and yes, I think we should file this as a bug. If you have the time, it would be much appreciated!

**Comment by AndersEkl** [comment]
Ok, so is `<details>` our preferred option now? Should we have both the old option and `<details>`?

**Comment by martinpub** [comment]
We still wait for Oscar to deliver some testing results using MO, he mentioned it but I don't remember the details. I think we should go for this and make sure RS we target process it correctly when using MO or Read Aloud. Ping @oscarlcarlsson @lindheli

**Comment by jonaslil** [comment]
Some further test results: In the Colibrio Vanilla Reader, details works fine in read aloud. The content is read even if the element is closed, and you can open the element while using read aloud.

Colibrio does, however, have display issues with details when the content is too large to fit on the current page (e.g. a table). In the Vanilla Reader the content gets clipped, in the Android app only a part of the content is displayed, and then the details element is repeated on the next page, showing more of the content. The experience is confusing.

At Celia, we don't have epub support in our app and online player yet, so can't test with them.

In view of the mixed RS support, I think we should keep the old model as an option if we choose to make details the default. (Or the other way around: details could be an option.)

But our view at Celia is that we should have the description outside of the figure element in order to handle issue #60

**Comment by oscarlcarlsson** [comment]
i think that details should be the option here, since it's not something that the current epub3-MO-players handle that well. there are some issues in thorium as well.

**Comment by AndersEkl** [comment]
I'll take care of this. Is #60 really an issue? Or is it just a matter of getting used to the order? In many cases I think a caption gives a good context to an image, so it could be beneficial to get that information first.

**Comment by oscarlcarlsson** [comment]
regarding #60, i think that it might vary depending on the image and the caption. having both options available gives us more room to work with this from title to title.

**Comment by oscarlcarlsson** [comment]
@jonaslil the tests i ran with details gave the same results as you got in colibrios vanilla reader. when i tried it in Thorium you couldn't expand the details text. it was still read aloud if skipability was not checked.

**Comment by AndersEkl** [comment]
I will describe placement as different options then... If descriptions are placed inside the `<figure>` element, the order must be as currently described. If you want the caption below the image, descriptions must be placed outside. Should `<details>` always be placed outside?

**Comment by jonaslil** [comment]
There is a passage in Daisy KB (quoted above) that says details may not work inside a figure element. I would probably go for always having it outside, to avoid any problems.

**Comment by AndersEkl** [comment]
@jonaslil Yeah, I remembered reading something like that... It was in the KB. Ok, but then I deal with this issue.

**Comment by AndersEkl** [comment]
I have written a suggestion. Please have a look at it, before I close this issue.

**Comment by oscarlcarlsson** [comment]
looks good to me!

**Comment by jonaslil** [comment]
Looks good! Two comments:

- If `details` is used, it should be linked to the image with aria-details, not aria-describedby. So we don't want to require the latter for all cases.
- There is no default placement for the `aside` (either after or inside `figure`). Then agency specific instructions probably need to specify a default. (I would prefer after as a default because it works for any placement of the figcaption.)

**Comment by AndersEkl** [comment]
Default was only in regards to `<aside>` being used.

**Comment by jonaslil** [comment]
Yes, I noted that. I wanted to raise the question if we need a default for the placement. Or if we can rely on this always being specified in agency specific or editing instructions.

**Comment by AndersEkl** [comment]
I changed the wording in the lead up to the example. Also changed the aria attributes. Please have a look.

**Comment by AndersEkl** [comment]
I don't want to have a default placement as I think us Ordering Organisations will have very different preferences.

**Comment by jonaslil** [comment]
> I changed the wording in the lead up to the example. Also changed the aria attributes. Please have a look.

Have committed and pushed? Can't see these changes.

**Comment by AndersEkl** [comment]
Comitted, but not pushed. Now it is. :)

**Comment by AndersEkl** [comment]
Added small corrections after discussion on meeting. Closing the issue.
