### ISSUE TITLE
Add an introductory section about how these guidelines are based on other resources

### ISSUE THREAD

**Issue by AndersEkl** [nlbdev/nordic-accessible-epub-guidelines#43]
I think we should have an introductory section where we describe how DAISY's Digital Publishing Knowledge Base and other resources are the basis of these guidelines.

**Comment by martinpub** [comment]
Add also references to the KB if we reuse some of the examples.

**Comment by martinpub** [comment]
This is WIP

**Comment by martinpub** [comment]
Have made a first effort here, please check.

What about this section?

https://github.com/nlbdev/nordic-accessible-epub-guidelines/blob/61dcad807786595c0c609e530e558e32d022eada/guidelines/guidelines.md?plain=1#L40-L44?

Perhaps it can be removed?

**Comment by martinpub** [comment]
> Perhaps it can be removed?

Decided on yes in meeting, closing.
