### ISSUE TITLE
Clarify WCAG conformance/non-conformance of alt text

### ISSUE THREAD

**Issue by AndersEkl** [nlbdev/nordic-accessible-epub-guidelines#46]
Clarify that the alt text described in these guidelines are not sufficiantly conforming to WCAG.

**Comment by martinpub** [comment]
No other WCAG crimes hopefully?

**Comment by AndersEkl** [comment]
Just the ACE warnings concerning landmark elements without unique names. Nothing else, that I know of.

**Comment by martinpub** [comment]
> Just the ACE warnings concerning landmark elements without unique names. Nothing else, that I know of.

Good!

**Comment by martinpub** [comment]
Hmm, why doesn't the keyword "closes" or "Closes" in the commit message close this issue?

**Comment by martinpub** [comment]
Ah, OK, only on pushing/merging to the main branch, according to [GitHub docs](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword):

> You can also use closing keywords in a commit message. The issue will be closed when you merge the commit into the default branch, but the pull request that contains the commit will not be listed as a linked pull request.

**Comment by martinpub** [comment]
Still a good idea to link the issue number in the commit message though, ping @AndersEkl, @oscarlcarlsson, @jonaslil. That way, it will be referenced in the issue.
