### ISSUE TITLE
Implement ReSpec to structure the guidelines

### ISSUE THREAD

**Issue by martinpub** [nlbdev/nordic-accessible-epub-guidelines#47]
[ReSpec](https://respec.org/docs/) is used to neatly structure/format technical specs. It is used by the W3C but not limited to W3C documents (DAISY use it for some documents).

I have done initial tests with ReSpec for our guidelines (based on 2020-1), and it seems we can preserve Markdown editing with a few modifications, so that we can enjoy the full benefits of ReSpec (formatting, simplified cross-linking to other specs, etc.).

I think it is a good candidate for the revised guidelines.

**Comment by AndersEkl** [comment]
I agree! I think we should use it.

**Comment by martinpub** [comment]
I thought I could start this already now, even if there are still some remaining issues. I have already made a test, and could investigate more in detail what should be done so that we don't lose time before sending the draft for review to the big group.

**Comment by AndersEkl** [comment]
Great!

**Comment by martinpub** [comment]
Hi @AndersEkl @jonaslil @oscarlcarlsson @lindheli, I have now prepared a draft using ReSpec. I worked on a separate branch but took the liberty to merge it into 2024-1.

The respecification involved some copyediting as I went along, but there will surely be things left to fix before publication, so in addition to getting feedback on the guidelines, you should plan for a thorough post-feedback editing/copyediting round.

[Here you can find a working copy of the respecified guidelines](https://raw.githack.com/nlbdev/nordic-accessible-epub-guidelines/2024-1/guidelines/doc_tools/nordic_guidelines-2024-1-main_wrapper.html), in their current state. You can use that URL when you send out the call for feedback. Any changes made to the 2024-1 will be reflected there immediately (or at least almost immediately, sometimes it takes some time before it's updated).

**Comment by AndersEkl** [comment]
I have only scrolled through it quickly, but it looks great at first glance! Great work, @martinpub !

**Comment by josteinaj** [comment]
Very nice, looks great! 🙂

**Comment by martinpub** [comment]
Thanks!

**Comment by martinpub** [comment]
Thanks @jonaslil!

**Comment by martinpub** [comment]
I close this issue, can be reopened, or make a new one for issues related to the respecification discovered in reviewing the document.
