### ISSUE TITLE
Clarify that ligatures should not be captured as unicode ligature chars

### ISSUE THREAD

**Issue by martinpub** [nlbdev/nordic-accessible-epub-guidelines#48]
We have seen examples where ligatures from the source copy are captured as dedicated unicode ligature chars (e.g. "ﬆ" (U+FB06) instead of "st"). We should clarify that we don't want this.

**Comment by AndersEkl** [comment]
Maybe we should have a section about general requirements of text content?

**Comment by martinpub** [comment]
Closing as I noted that this was the agreed workflow.
