### ISSUE TITLE
Document specific constructions that are not mentioned in the guidelines but are allowed in the validator ruleset

### ISSUE THREAD

**Issue by martinpub** [nlbdev/nordic-accessible-epub-guidelines#50]
For completeness sake, we should probably document currently undocumented features that are allowed in the validator, e.g. sentence markup (https://github.com/nlbdev/nordic-epub3-dtbook-migrator/pull/565), the line-by-line class for divs (https://github.com/nlbdev/nordic-epub3-dtbook-migrator/pull/454), etc. I think NLB added a variant for image descriptions, might be more.

Can be added to an informational appendix section or similar.

Note, first determine if any of these should be incorporated into the new guidelines revision, then see what's left.

**Comment by oscarlcarlsson** [comment]
i see no reason not to include line-by-line in the general guidelines.

sentence detection/markup is probably more relevant in an appendix or a Media overlays-section of the guidelines.

**Comment by martinpub** [comment]
The commit above added sentence markup.

I will go ahead and add the line-by-line inside the guidelines, according to #28.

The NLB variant for image descriptions is depending on #4, so I will not address it until we know exactly what the general prescribed image description variant should be. Perhaps it's not really an issue for 2024-1, if we change the general method (ping @josteinaj)?

I will check the schema revision history for additional things before closing this issue.

**Comment by martinpub** [comment]
I have now reviewed [the schema revision history](https://github.com/nlbdev/nordic-epub3-dtbook-migrator/commits/v2.0.1/src/main/resources/xml/schema/2020-1) and could not find any additional things to list in an appendix.

I leave this open until #4 is solved, or we get feedback from NLB that they don't need it in 2024-1.

**Comment by josteinaj** [comment]
From the top of my head, I don't remember anything about NLB specific image descriptions. Is there something about it in the schemas or in a Github issue?

@eliseaas might know more?

**Comment by martinpub** [comment]
No worries, let me refresh your memory ;)

Here is the commit: https://github.com/nlbdev/nordic-epub3-dtbook-migrator/commit/621fd265bf5f05b5883dbd143b26093f57ec3cf3

This is the connected issue: https://github.com/nlbdev/nordic-epub3-dtbook-migrator/issues/502

**Comment by josteinaj** [comment]
Thanks for the refresher! :)

As far as I know, I don't think this is something we use. But I can't with certainty confirm it.

@eliseaas: do you know if we use `<details>` and `<summary>` elements for extended image descriptions? Can you confirm whether or not we use it and whether or not we need it in the next guidelines revision?

**Comment by eliseaas** [comment]
We don't currently use or need neither `<details>` nor `<summary>` elements. I can't imagine we would need them in the next revision, either.

**Comment by martinpub** [comment]
Thanks for confirming @eliseaas!

**Comment by martinpub** [comment]
Closing as the list of undocumented features is now exhausted.
