### ISSUE TITLE
Review of 3.1 Structural Divisons and Semantics

### ISSUE THREAD

**Issue by TorilBWM** [nlbdev/nordic-accessible-epub-guidelines#55]
This is to partly reopen issue 42 from the old repo. We shared the text in our guidelines on the thematic grouping of content and use of the `<section>` element, which resulted in 3.1 Structural Divisions and Semantics in the NG2020 version.
We would like this section to specifically mention tasks and solutions, along the lines of:
It is important to make sure every task and every solution is marked up with its own end of section.

**Comment by AndersEkl** [comment]
We see no need to go into specifics about exercises or other type of tasks, but the issue with placement of end of section will be addressed and is covered in #34 .

**Comment by AndersEkl** [comment]
If certain content is to be marked up as their own sections or not will be up to each ordering agency and if it is not evident from the layout of the source material it will need to be clarified through either editing instructions or more general agency-specific guidelines.
