### ISSUE TITLE
Add requirement for splitting headings in main heading and heading subtitle

### ISSUE THREAD

**Issue by martinpub** [nlbdev/nordic-accessible-epub-guidelines#58]
[The KB suggests to separate the heading title from a subtitle](http://kb.daisy.org/publishing/docs/html/headings.html#ex-02), e.g. "Chapter one. The beginning of a long journey", with `<hgroup>` wrapping and `<h[x]>` for the main heading and `<p role="doc-subtitle">` for the heading subtitle.

We already have a similar structure for title pages in 3.3.2. Perhaps we should update it to use the above structure, but also extend it to at least chapter or part headings?

**Comment by AndersEkl** [comment]
Specify how these headings are to be included in the navigation document.

**Comment by AndersEkl** [comment]
Look into validation errors from Epubcheck.

**Comment by martinpub** [comment]
@jonaslil Which version of EpubCheck did you use? I don't get any errors with EpubCheck v5.1.0 and this markup:

```
<hgroup>
  <h1 id="h1_14">ELFTE KAPITLET.</h1>
  <p role="doc-subtitle">Spökhistorier.</p>
</hgroup>
```

**Comment by AndersEkl** [comment]
That is great! Then I think we definitely should include the `<hgroup>` markup in the guidelines.

**Comment by martinpub** [comment]
OK great! Let's go for it.
