### ISSUE TITLE
Elaborate the section covering EPUB landmarks

### ISSUE THREAD

**Issue by AndersEkl** [nlbdev/nordic-accessible-epub-guidelines#59]
Clarify what should be included in the landmarks section of the navigation document. Establish a canonical labelling of the landmark entries.

**Comment by oscarlcarlsson** [comment]
A question that has occurred here lately is where the "start of content" landmark should be places. shouldn't a prologue be counted as a part of the main content? for fiction, i'd personally count prologues/prefaces as a part of the main content.

**Comment by oscarlcarlsson** [comment]
I had a closer look at our current guidelines. Under 3.1 Structural Divisons and Semantics we link to https://idpf.github.io/epub-vocabs/structure/ where they have a list of sections that typically occur in bodymatter. Preface, introduction etc. is included in this list. If "Start of content" is supposed to start with the first bodymatter-file, then this is already sorted in the current guidelines and might just need some clarification.

PS. I'm aware that the link is referencing an old version of the w3c-document. But it's the same in the latest version.

**Comment by jonaslil** [comment]
We agreed in the editors meeting on some points about this issue: landmarks should not be a required nav element, a landmark nav should only be included when specifically requested, and we won't give a detailed instruction about labels etc. in the guidelines. I rewrote the section on landmarks today based on these ideas.

**Comment by martinpub** [comment]
Excellent, great work @jonaslil!
