### ISSUE TITLE
All caps in headers and other text content

### ISSUE THREAD

**Issue by jonaslil** [nlbdev/nordic-accessible-epub-guidelines#61]
A recurring quality issue in our epubs is the use of hard-coded all caps especially in headings. This creates inconsistencies in the TOC, affects readability and styling adversely, and may also be a problem for screenreader users. I think we should at least discourage this for headings and entire paragraphs. Single words within paragraphs are less of a problem.

**Comment by martinpub** [comment]
Partly covered by #15

**Comment by jonaslil** [comment]
Closing this and the related #15 , just reopen if you have anything to add.
