### ISSUE TITLE
Define a general rule for composing labels for untitled chapter sections

### ISSUE THREAD

**Issue by martinpub** [nlbdev/nordic-accessible-epub-guidelines#62]
Decision is to use MTM's current algorithm:

> For bodymatter sections where no heading is available in the source copy, the Nordic Guidelines require labels to be created and stored in an @aria-label attribute in the heading section. For MTM productions, if nothing else is mentioned in accompanying Editing Instructions, we kindly request our producers to name the untitled sections using the first three words of the chapter text, followed by a space and an ellipsis, e.g. aria-label="Det var längesedan …" for a bodymatter section where the first three words of the body text are "Det var längesedan".

**Comment by martinpub** [comment]
See also #6

**Comment by josteinaj** [comment]
What if there are no sections? One example is the Discworld novels. They're just a series of paragraphs, separated by thematic breaks. Should producers put the whole book in one big chapter or should they group the content into untitled sections? If so, should there be some suggestions about using thematic breaks as possible break points when creating sections? I think it is useful to create sections, not only for being able to navigate the book (navigating by page breaks is always an option), but mainly for performance reasons. If you open an e-book on a reading system such as Kindle, Kobo or Pocketbook, you will get very sluggish performance. Especially when changing font size and navigating between big content files.

**Comment by martinpub** [comment]
This issue is not addressing section boundaries as such, I think the assumption is that sections are already created for separating the book into smaller chunks (e.g. chapters). This is just about the labelling of those sections.

**Comment by josteinaj** [comment]
Ok, I created a separate issue for it: https://github.com/nlbdev/nordic-accessible-epub-guidelines/issues/65

**Comment by martinpub** [comment]
I will add something along the lines of "this method can also be used in cases where there are untitled sections on levels below chapter".

**Comment by martinpub** [comment]
I tried to update but I realise 

> I will add something along the lines of "this method can also be used in cases where there are untitled sections on levels below chapter".

is potentially in conflict with the current text

> No sub-sections of any content document should have an `aria-label` or `aria-labelledby` attribute, unless specific instructions are given by the Ordering Agency.

Any ideas?

**Comment by oscarlcarlsson** [comment]
As long as it's allowed to include aria-labels on sub sections I guess we can keep it on an editing instruction-level.

**Comment by martinpub** [comment]
OK great.
