### ISSUE TITLE
Decide on general structure for frontmatter sections

### ISSUE THREAD

**Issue by martinpub** [nlbdev/nordic-accessible-epub-guidelines#63]
Continuing the discussion from #25.

Oscar and Jonas will share examples.

**Comment by jonaslil** [comment]
Answering question in #25:

Yes, I think the front cover should be in its own xhtml file. It will contain only one section, no need for nesting sections for different cover parts anymore.

The backcover text and possible other cover texts (flaps) will be in another xhtml file, the one with "frontmatter" in the file name. Not quite sure about how the section markup should be in this file.

Looking at our current Daisy books, I see no separation of these different cover texts, only one section called "Kustantaja esittelee" (in swedish: "Förlaget presenterar"). Based on this, we probably don't need detailed markup separating different cover text parts.

**Comment by oscarlcarlsson** [comment]
I have updated the cover and back cover section. Let me know if anything should be clarified.
