### ISSUE TITLE
How to mark up books with no sections?

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/nordic-accessible-epub-guidelines#65]
What if there are no sections? One example is the Discworld novels. They're just a series of paragraphs, separated by thematic breaks. Should producers put the whole book in one big chapter or should they group the content into untitled sections? If so, should there be some suggestions about using thematic breaks as possible break points when creating sections? I think it is useful to create sections, not only for being able to navigate the book (navigating by page breaks is always an option), but mainly for performance reasons. If you open an e-book on a reading system such as Kindle, Kobo or Pocketbook, you will get very sluggish performance. Especially when changing font size and navigating between big content files.

**Comment by AndersEkl** [comment]
Add a text explaining that the Ordering Agency must provide instructions in these cases.

**Comment by AndersEkl** [comment]
Closing this. There is a section about untitled section that in combination with editing instructions can resolve this when it happens.
