### ISSUE TITLE
Allow numbering for paragraphs in validator.

### ISSUE THREAD

**Issue by oscarlcarlsson** [nlbdev/nordic-accessible-epub-guidelines#68]
Earlier I've run in to some titles with numbered paragraphs. These cannot be properly marked up and still pass our validation since `<span class="linegroup">` is only allowed in `<span class="line">`. 
Should we add a `<span class="parnum">` for numbered paragraphs ´?

Should this be added to #28 ?

**Comment by jonaslil** [comment]
Yes the validator needs to allow `<span class="parnum">` in `p class="linegroup"`, if this is what you mean.

Adding the class to the guidelines was addressed in #52

The solution I suggested for prose in the guidelines draft is this:

```html
<p class="numbered"><span class="parnum">1</span>Paragraph text.</p>
```

**Comment by oscarlcarlsson** [comment]
can't we just keep using `<p class="linegroup">`? the titles i've run into have only had each fith paragraph numbered. 
otherwise, should all of the paragraphs use the class "numbered" or only the ones with a parnum?

**Comment by oscarlcarlsson** [comment]
closed since this was already added to the guidelines in another closed issue.
