### ISSUE TITLE
Additions to the poetry and verse section

### ISSUE THREAD

**Issue by AndersEkl** [nlbdev/nordic-accessible-epub-guidelines#7]
Add text about when to capture a piece of poetry as an image.

**Comment by AndersEkl** [comment]
Maybe also add the opportunity to use preformatted text?

**Comment by AndersEkl** [comment]
I am going to add the text about when to also capture a poem as an image. But what do we say about pre-formatted text? Is this something we want? @martinpub @jonaslil @oscarlcarlsson @lindheli

**Comment by AndersEkl** [comment]
Yeah, only when specifically instructed. I'll add that. Will just be a short paragraph or two.

**Comment by martinpub** [comment]
Great!

**Comment by oscarlcarlsson** [comment]
sounds great!
