### ISSUE TITLE
.svg

### ISSUE THREAD

**Issue by indixcss** [nlbdev/nordic-accessible-epub-guidelines#72]
@AndersEkl @martinpub @TorilBWM
https://github.com/nlbdev/epub3-guidelines-update/issues/35
"Now we require that pictures are to be extracted as .jpeg or .png. Could we include that "if possible, extract pictures as .svg" ... "

This issue was considered a good candidate for v. 2.0
https://github.com/nlbdev/epub3-guidelines-update/issues/35#issuecomment-706102287) 

Statped would welcome including .svg images

**Comment by oscarlcarlsson** [comment]
I see no reason not to include this. It's probably a good safegard for future productions.

**Comment by AndersEkl** [comment]
It depends on if there are viable tools to capture an image as .svg. We have not mentioned .svg as a requirement previously, and if it is something that takes more effort to deliver, I am not sure we can just add it as a requirement just like that.

Does anyone know of any tools for this?

**Comment by AndersEkl** [comment]
I have already added a text about existing SVG images may be kept as such, if requests are made by the ordering agency.

**Comment by AndersEkl** [comment]
It is in the section about image requirements, a new subsection at the end. Use the reSpec version. That is where it is added.

We do allow the format, but an ordering agency needs to request it. Some agencies don't want it.
